"""Ports for future provider runtimes. Untrusted documents remain data, never authority."""

from typing import Any, Protocol

from adaptive_alpha.domain import Hypothesis, StrategySpec


class ResearchConnector(Protocol):
    capabilities: frozenset[str]

    async def search(self, query: str) -> list[dict[str, Any]]: ...
    async def get_document(self, document_id: str) -> dict[str, Any]: ...
    async def get_metadata(self, document_id: str) -> dict[str, Any]: ...
    async def get_references(self, document_id: str) -> list[str]: ...
    async def get_citations(self, document_id: str) -> list[str]: ...


class LLMProvider(Protocol):
    async def propose(
        self, objective: str, evidence: tuple[str, ...], token_budget: int
    ) -> Hypothesis: ...


class EngineeringAgent(Protocol):
    def propose_implementation(self, spec: StrategySpec) -> dict[str, Any]: ...
    def implement(self, spec: StrategySpec) -> dict[str, Any]: ...
    def fix_tests(self, artifact_id: str) -> dict[str, Any]: ...
    def create_tool(self, description: str) -> dict[str, Any]: ...
    def analyze_failure(self, evidence: dict[str, Any]) -> str: ...
