const labels={RESEARCH:'Исследование',LAB_VALIDATED:'Лаборатория пройдена',SHADOW:'Наблюдение',PAPER:'Бумажная торговля',CHALLENGER:'Претендент',ACTIVE_LIMITED:'Активная paper-стратегия',DEMOTED:'Приостановлена',RETIRED:'Архив'};
const next={RESEARCH:'LAB_VALIDATED',LAB_VALIDATED:'SHADOW',SHADOW:'PAPER',PAPER:'CHALLENGER'};
export function operationsUI({$,escape,table,empty,stamp,post,api,action,refresh,toast}){
 let state,selected;
 function render(lifecycle,engineering,readiness){
  state=lifecycle;
  const cards=lifecycle.strategies.map(s=>{
   const comparison=lifecycle.comparisons.find(c=>c.challenger_id===s.candidate_id&&c.verdict==='PASS'&&(c.challenger_validation_after||null)===(s.validation_after||null));
   const target=next[s.status]||(s.status==='CHALLENGER'&&comparison?'ACTIVE_LIMITED':null);
   return `<article class="strategy-card"><span class="pill ${s.status==='ACTIVE_LIMITED'?'teal':'neutral'}">${escape(labels[s.status])}</span><h3>${escape(s.name)}</h3><p>${escape(s.symbol)} · версия ${s.version} · внутренняя симуляция</p>${target?`<button class="secondary" data-stage="${target}" data-candidate="${escape(s.candidate_id)}">${escape(labels[target])} →</button>`:''}${s.status==='RESEARCH'&&s.validation_after?`<button class="secondary" data-revalidate="${escape(s.candidate_id)}">Повторная проверка</button>`:''}${s.forward_eligible?`<button class="danger" data-stage="DEMOTED" data-candidate="${escape(s.candidate_id)}">Приостановить</button>`:''}${s.status==='DEMOTED'?`<button class="secondary" data-stage="RESEARCH" data-candidate="${escape(s.candidate_id)}">Вернуть на исследование</button><button class="secondary" data-stage="RETIRED" data-candidate="${escape(s.candidate_id)}">В архив</button>`:''}</article>`;
  });
  cards.push(...lifecycle.unregistered.map(s=>`<article class="strategy-card"><h3>${escape(s.name)}</h3><p>Кандидат предыдущей версии лаборатории.</p><button class="secondary" data-register="${escape(s.candidate_id)}">Добавить в реестр</button></article>`));
  $('lifecycle-strategies').innerHTML=cards.join('')||empty('Стратегий пока нет.','Результаты исследования появятся здесь.');
  $('performance-strategies').innerHTML=lifecycle.strategies.map(s=>`<p>${escape(s.name)} · <button class="text-button" data-performance="${escape(s.candidate_id)}">Проверить результаты</button></p>`).join('')||empty('Наблюдений пока нет.','Мониторинг начинается после выбора активной paper-стратегии.');
  for(const [id,entries,label] of [['comparison-challenger',lifecycle.strategies.filter(s=>['SHADOW','PAPER','CHALLENGER'].includes(s.status)),'Выберите претендента'],['comparison-active',lifecycle.strategies.filter(s=>s.status==='ACTIVE_LIMITED'),'Деньги без позиции — первый запуск']]){
   const old=$(id).value;$(id).innerHTML=`<option value="">${label}</option>`+entries.map(s=>`<option value="${escape(s.candidate_id)}">${escape(s.name)} · ${escape(s.symbol)}</option>`).join('');if(entries.some(s=>s.candidate_id===old))$(id).value=old;
  }
  $('strategy-comparisons').innerHTML=lifecycle.comparisons.length?table(['Претендент','Наблюдения','Результат','Данные'],lifecycle.comparisons.map(c=>`<tr><td>${escape(lifecycle.strategies.find(s=>s.candidate_id===c.challenger_id)?.name||c.challenger_id)}</td><td>${c.matched_days} / ${c.policy.minimum_days} дней</td><td><button class="text-button" data-comparison="${escape(c.id)}">${escape(c.verdict)}</button></td><td>${escape(c.origin||'Ожидаются')}</td></tr>`)):empty('Сравнений пока нет.','Зарегистрируйте пару до начала наблюдения.');
  $('lifecycle-events').innerHTML=lifecycle.transitions.map(e=>`<div class="audit-event"><time>${stamp(e.at)}</time><div>${escape(labels[e.from])} → ${escape(labels[e.to])}<p>${escape(e.reason)}</p></div><small>${escape(e.actor)}</small></div>`).join('')||empty('Переходов пока нет.','Каждое решение сохраняется с причиной.');
  $('engineering-attempts').innerHTML=engineering.attempts.length?table(['Запуск','Состояние','Доставки','Этап','Бюджет'],engineering.attempts.map(a=>`<tr><td>${escape(a.id.slice(0,24))}<small>${stamp(a.created_at)}</small></td><td>${escape(a.status)}<small>${escape(a.reason||'')}</small></td><td>${a.delivery?.deliveries??0}<small>${escape(a.delivery?.status||'QUEUED')}</small></td><td>${escape(a.stage)}</td><td>${a.budget.tokens} токенов · ${a.budget.seconds} с</td></tr>`)):empty('Инженерных запусков пока нет.','Каждый запуск будет сохранён до обращения к Ouroboros.');
  const toolWorker=engineering.tool_worker||{},toolWorkerActive=toolWorker.heartbeat&&Date.now()/1000-toolWorker.heartbeat<90&&toolWorker.ready;
  $('engineering-tool-runs').innerHTML=`<h3>Проверка harness в изолированном runner</h3><p class="fine-print">${toolWorkerActive?'Tool worker готов; production-профиль использует runsc.':'Tool worker не допущен или не отвечает. Запуски сохраняются, но исполняться не будут до настройки gVisor.'}</p>`+(engineering.tool_runs?.length?table(['Задание','Артефакт','Состояние','Доставки','Результат'],engineering.tool_runs.map(r=>`<tr><td>${escape(r.id.slice(0,24))}<small>${stamp(r.created_at)}</small></td><td>${escape(r.artifact_id.slice(0,24))}</td><td>${escape(r.status)}<small>${escape(r.reason||'')}</small></td><td>${r.deliveries??0}</td><td>${escape(r.result?.report?.status||'—')}</td></tr>`)):empty('Проверок harness пока нет.','Оператор может поставить отрецензированный harness в устойчивую очередь через API.'));
  $('engineering-orders').innerHTML=engineering.work_orders.map(w=>`<details><summary>${escape(w.spec.name)} · инженерное задание</summary><p>${escape(w.spec.hypothesis)}</p><p>${escape(w.spec.decision_rules.join('; '))}</p></details>`).join('')||empty('Заданий пока нет.','Выберите инженера Ouroboros при запуске кампании.');
  $('engineering-artifacts').innerHTML=engineering.artifacts.map(a=>{const b=engineering.benchmarks.find(b=>b.artifact_ids.includes(a.id)&&b.passed),reviewed=a.reviews?.length;return `<article class="strategy-card"><span class="pill neutral">${escape(a.kind)}</span><h3>${escape(a.name)}</h3><p>${a.kind==='strategy'?'Ограниченная программа сигнала':a.kind==='harness'?'Harness для отдельной sandbox-проверки':'Предложение для рецензирования'}</p><p>${reviewed?'Рецензия оператора сохранена.':'Ожидает рецензии оператора.'}</p><details><summary>Исходный текст</summary><pre>${escape(a.source)}</pre></details>${b&&!reviewed?`<button class="secondary" data-artifact="${escape(a.id)}" data-benchmark="${escape(b.id)}">Зафиксировать рецензию</button>`:''}</article>`;}).join('');
  const runtime=readiness.worker?.engineering_runtime,queue=readiness.engineering_worker||{},queueActive=queue.heartbeat&&Date.now()/1000-queue.heartbeat<90;
  $('engineering-readiness').textContent=(runtime?.ready?`Ouroboros ${escape(runtime.upstream_version||'')} готов к исполнению в изолированном workspace.`:runtime?.configured?`Ouroboros подключён, исполнение закрыто: ${escape(runtime.reason||'профиль модели не допущен')}.`:'Ouroboros пока не подключён. Для этого режима нужны изолированное окружение инженера и ключ модели исследователя.')+` Инженерная очередь: ${queueActive?'worker работает':'worker не отвечает'}.`;
 }
 document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;action(async()=>{
  if(b.dataset.register){await post(`/lifecycle/${encodeURIComponent(b.dataset.register)}/register`);await refresh();}
  if(b.dataset.stage){const s=state.strategies.find(s=>s.candidate_id===b.dataset.candidate);if(!s)return;selected={candidate_id:s.candidate_id,target:b.dataset.stage,expected_version:s.version,request_id:crypto.randomUUID(),comparison_id:state.comparisons.find(c=>c.challenger_id===s.candidate_id&&c.verdict==='PASS'&&(c.challenger_validation_after||null)===(s.validation_after||null))?.id||null};$('lifecycle-title').textContent=labels[selected.target];$('lifecycle-description').textContent=`${s.name}. Сервер проверит доказательства и актуальную версию. Реальный капитал недоступен.`;$('lifecycle-reason').value='';$('lifecycle-dialog').showModal();}
  if(b.dataset.revalidate){const s=state.strategies.find(s=>s.candidate_id===b.dataset.revalidate);if(!s)return;selected={candidate_id:s.candidate_id,target:'REVALIDATE',expected_version:s.version,request_id:crypto.randomUUID()};$('lifecycle-title').textContent='Повторная проверка';$('lifecycle-description').textContent=`${s.name}. Повторный запуск на сохранённых данных использует бюджет независимой оценки. Он не возобновляет стратегию и не заменяет наблюдения на новых котировках.`;$('lifecycle-reason').value='';$('lifecycle-dialog').showModal();}
  if(b.dataset.comparison){const r=await api(`/strategy-comparisons/${encodeURIComponent(b.dataset.comparison)}`);$('detail-title').textContent='Доказательства сравнения';$('detail-content').innerHTML=`<pre>${escape(JSON.stringify(r,null,2))}</pre>`;$('download-evidence').hidden=true;$('detail-dialog').showModal();}
  if(b.dataset.performance){const r=await api(`/lifecycle/${encodeURIComponent(b.dataset.performance)}/performance`);const states={NOT_ACTIVATED:'Стратегия ещё не была активирована',WARMUP:'Собираются новые наблюдения',HEALTHY:'Порог остановки не достигнут',WARNING:'Предупреждение: первый период ухудшения',HALT:'Подтверждённое ухудшение — остановка',INCONCLUSIVE:'Недостаточно сопоставимых данных'};const percent=v=>`${(v*100).toFixed(2)}%`;$('detail-title').textContent='Контроль результатов';$('detail-content').innerHTML=`<p>${escape(states[r.monitor.status]||r.monitor.status)}</p><p>Текущее состояние: ${escape(labels[r.lifecycle_status])}. Только внутренняя симуляция.</p>`+(r.reports.length?table(['Период','После издержек','Ориентир','Решение'],r.reports.map(w=>`<tr><td>${stamp(w.window_start)} — ${stamp(w.window_end)}</td><td>${percent(w.net_return)}</td><td>${percent(w.reference_window_return)}</td><td>${escape(states[w.status])}</td></tr>`)):empty('Завершённых периодов пока нет.','Для первого вывода нужно 11 дневных наблюдений после активации.'))+`<details><summary>Наблюдения и основания решения</summary><pre>${escape(JSON.stringify(r,null,2))}</pre></details>`;$('download-evidence').hidden=true;$('detail-dialog').showModal();}
  if(b.dataset.artifact){await post(`/engineering/artifacts/${encodeURIComponent(b.dataset.artifact)}/promote`,{benchmark_id:b.dataset.benchmark});toast('Рецензия сохранена. Она не даёт торгового допуска или права запускать произвольный код.');await refresh();}
 });});
 $('lifecycle-close').onclick=()=>$('lifecycle-dialog').close();
 $('lifecycle-form').onsubmit=event=>{event.preventDefault();action(async()=>{if(!selected)return;const {candidate_id,...body}=selected;if(body.target==='REVALIDATE'){const result=await post(`/lifecycle/${encodeURIComponent(candidate_id)}/revalidate`,{expected_version:body.expected_version,request_id:body.request_id,reason:$('lifecycle-reason').value});toast(`Повторная проверка: ${result.status}. Результат сохранён; дальнейший допуск требует отдельного решения.`);}else{await post(`/lifecycle/${encodeURIComponent(candidate_id)}/transitions`,{...body,reason:$('lifecycle-reason').value});toast('Решение и доказательства сохранены.');}$('lifecycle-dialog').close();await refresh();});};
 $('comparison-form').onsubmit=event=>{event.preventDefault();action(async()=>{await post('/strategy-comparisons',{active_id:$('comparison-active').value||null,challenger_id:$('comparison-challenger').value});await refresh();toast('Условия сравнения зафиксированы. Собираются новые наблюдения.');});};
 return {render};
}
